[LER-27] - Toast Component
sirius-valley/lerni-mobile pull request #14
Opened 2024-01-10 20:08 UTC by schcolnikj

2024-01-11 19:22 UTC, dipietronicolas commented on src/app/(tabs)/profile/index.tsx
> +        children="show error toast"
Esto de children lo hicimos asi para poder envolver el texto que queremos que sea el label del boton. Deberia ser algo como: 

`<Button>
  show error toast
</Button>
`

2024-01-11 19:43 UTC, dipietronicolas commented on src/components/styled/Toast/ToastText/styles.ts
> +`;
Aca hay dos cosas, la primera es que el css esta mal escrito y el emulador me tira error en esas propiedades. Son font-family, font-size y font-weight. 
Y la segunda es que ni hace falta pasarle esas propiedades si le pasaras el StyledText en lugar de Text, que ya esta preparado para recibir "variant".

quedaria 
```
export const ToastText = styled(StyledText)`
gap: 16px;
color: ${(props) => props.theme.white};
`
```

2024-01-11 19:53 UTC, dipietronicolas commented on src/hoc/Toast.tsx
> +      }, 2000000);
Es un monton de tiempo esto, se que no hay una definicion sobre cuanto tiempo tenga que permanecer el toast, pero aprox entre 3 y 4 segundos deberia ser un tiempo prudente.

2024-01-11 19:55 UTC, dipietronicolas commented on src/redux/slice/utils.slice.ts
> +  text?: string;
Hay algun motivo para que estos estados sean opcionales? no podrian tener un valor por defecto?

2024-01-11 20:00 UTC, schcolnikj commented on src/redux/slice/utils.slice.ts
> +  text?: string;
mmm, no deberían tener valor por defecto. Esta opcional porque depende del estado en redux que se resetea a undefined con el timeout.

2024-01-11 20:02 UTC, dipietronicolas requested changes
Review comments

2024-01-12 12:16 UTC, dipietronicolas approved these changes

2024-01-12 12:33 UTC, fabrizioserial commented on src/components/styled/Toast/ToastIcon/index.tsx
> +const ToastIcon = ({ type }: ToastIconProps) => {
Estos iconos podriamos hacerlos un SVG en vez de que sean un text. La ventaja seria de que el icono ahora no va a depender del OS del dispositivo.
![image](https://github.com/sirius-valley/lerni-mobile/assets/56046397/82799e3d-3081-4730-94b7-679af0d73d67)

2024-01-12 12:43 UTC, merged