[LER-24] Chat Bubbles
sirius-valley/lerni-mobile pull request #16
Opened 2024-01-11 19:23 UTC by schcolnikj

**Description**

We have different types of bubbles to display in a pill. Text and image are two of the most common.

-  The text bubble can be used by tutors and students.

-  The image bubble is used by tutors.

**Acceptance Criteria**

- [✔️] - Text bubble for students
- [✔️] - Text bubbles for tutors
- [✔️] - Image bubble for tutors
- [✔️] - The last bubble of an answer, must have a image that reference the tutor or yourself

2024-01-14 20:37 UTC, fabrizioserial commented on src/components/styled/TextBubble/ImageBubble/styles.ts
> +export const ImageBubble = styled.Image<MessageProps>`
Todos los componentes que son de StyledComponents, agreguemosle el "Styled" adelante en el nombre -> `StyledImageBubble`

2024-01-14 20:37 UTC, fabrizioserial commented on src/components/styled/Avatar/AvatarContainer/styles.ts
> +export const AvatarContainer = styled.View<MessageProps>`
este file puede estar en Avatar/styles.ts

2024-01-14 20:41 UTC, fabrizioserial commented on src/components/styled/TextBubble/index.tsx
> +export const StyledTextBubble = ({
Este no deberia llamarse StyledTextBubble. Lo llamaria mas como <BubbleComponent/> o algo asi.. Por lo que veo, este va a ser el componente que va a renderizar las demas bubbles en base a su "type"

2024-01-14 20:42 UTC, fabrizioserial commented on src/components/styled/TextBubble/index.tsx
> +      {type === 'text' && (
Esto lo pensaria mas como un Switch, que como un if anidado

2024-01-14 20:44 UTC, fabrizioserial commented on src/components/styled/Avatar/index.tsx
> +    <AvatarContainer user={user}>
Pondria directamente que el StyledAvatarContainer sea el componente Imagen.. No le veo util que sea un` View > Image`

2024-01-14 20:44 UTC, fabrizioserial commented on src/components/styled/Avatar/index.tsx
> +            uri: uri,
hagamos que si no existe uri, le pongamos un default image

2024-01-14 20:45 UTC, fabrizioserial commented on src/components/styled/TextBubble/index.tsx
> +      {isLast && <Avatar user={user} />}
habria que arreglar esta logica

2024-01-15 16:50 UTC, dipietronicolas commented on src/app/(tabs)/profile/index.tsx
> +import { Text, View } from 'react-native';
importaste un View que no estas usando, estaria bueno sacarlo

2024-01-15 16:50 UTC, dipietronicolas commented on package.json
> +    "react-native-svg": "14.1.0",
1. Por que estamos borrando react-native-toast-message?
2. En [este pr](https://github.com/sirius-valley/lerni-mobile/pull/14/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) de la semana pasada bajaste la version de react-native-svg de la 14 a la 13, por que ahora la estamos subiendo de nuevo? 

Todos estos cambios estaria bueno que vengan aclarados en la descripcion del PR.

2024-01-15 16:51 UTC, dipietronicolas commented on src/components/styled/Avatar/index.tsx
> +  // uri = 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250';
Borrar

2024-01-15 16:54 UTC, dipietronicolas commented on src/components/styled/ChatBubble/ImageBubble/styles.ts
Para este componente ChatBubble estas usando una estructura de carpetas diferente que para la de Avatar, donde tenes un archivo index y su correspondiente archivo styles.ts. Aca estas metiendo los archivos styles.ts adentro de carpetas, deberiamos seguir la misma estructura para todos los componentes. Igual que como lo hiciste en Avatar.

2024-01-15 16:55 UTC, dipietronicolas requested changes
..

2024-01-15 18:28 UTC, dipietronicolas approved these changes
LGTM

2024-01-15 18:32 UTC, merged