[LER-23] - Program card
sirius-valley/lerni-mobile pull request #18
Opened 2024-01-12 16:38 UTC by valenchus

To easily test this PR:
1) you can download an image and put into the assets/images folder
2) then, replace the source from the image to: source={require('../../../../assets/images/your-image.jpeg')}
3) check the 3 different program cards by adding to a file:

      <StyledRow
        css={{ padding: 20, gap: 10, background: theme.primary900, width: 400, height: 200 }}
      >
        <ProgramCard id="uno" title="Programa 1" imgUrl="as" status="completed" progress={0.4} />
        <ProgramCard id="dos" title="Programa 2" imgUrl="as" status="in_progress" progress={0.1} />
        <ProgramCard id="tres" title="Programa 3" imgUrl="as" status="not_started" progress={0.2} />
      </StyledRow>

2024-01-14 20:46 UTC, fabrizioserial commented on assets/icons/HeartPill.tsx
> +const HeartPill = ({ status }: PillProps) => {
Eliminar este componente

2024-01-14 20:46 UTC, fabrizioserial commented on assets/icons/types.ts
> +export interface PillProps {
porque aca esto?

2024-01-14 20:48 UTC, fabrizioserial commented on src/components/program/ProgramCard/index.tsx
> +    <>
Este fragment no hace falta

2024-01-14 20:49 UTC, fabrizioserial commented on src/components/program/ProgramCard/index.tsx
> +          <Image style={{ width: 109, height: 109 }} source={{ uri: imgUrl }}></Image>
Esto puede tener un Self-Closing  `<image ... />`

2024-01-15 15:08 UTC, dipietronicolas commented on src/components/program/ProgramCard/index.tsx
> +        <Image style={{ width: 109, height: 109 }} source={{ uri: imgUrl }} />
borderRadius is missing

2024-01-15 15:09 UTC, dipietronicolas requested changes
..

2024-01-15 15:37 UTC, dipietronicolas approved these changes
LGTM

2024-01-15 16:20 UTC, merged